# Generated by Django 5.0 on 2023-12-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
