# Generated by Django 5.0 on 2023-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('val', '0002_participant_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='profile_picture',
        ),
    ]
