# Generated by Django 5.0 on 2023-12-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val', '0003_remove_participant_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
