# Generated by Django 5.0 on 2023-12-20 16:25

import val.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val', '0004_participant_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, validators=[val.models.validate_ur_ac_rw_email]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=20, validators=[val.models.validate_valid_phone_number]),
        ),
    ]
