# Generated by Django 5.0 on 2023-12-20 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val', '0005_alter_participant_email_alter_participant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
